export default {
  searchForm: document.querySelector('.search__form'),
  formInput: document.querySelector('.form__input'),
  formAddToFavorites: document.querySelector('.form__add-to-favorites'),
  formIconStar: document.querySelector('.form__icon-star'),
  favoritesArrowLeft: document.querySelector('.favorites__arrow-left'),
  favoritesList: document.querySelector('.favorites__list'),
  searchFavorites: document.querySelector('.search__favorites'),
  currentWeather: document.querySelector('.js-current-weather'),
  body: document.querySelector('body'),
  geoModal: document.querySelector('.geolocation'),
  forecastToday: document.querySelector('.forecast'),
  forecastFiveDays: document.querySelector('.forecast__five-days'),
  switchDaysBtn: document.querySelector('.switch-days-btn'),
};
