export default {
  search: document.querySelector('.search'),
  searchForm: document.querySelector('.search__form'),
  formInput: document.querySelector('.form__input'),
  formAddToFavorites: document.querySelector('.form__add-to-favorites'),
  formIconStar: document.querySelector('.form__icon-star'),
  favoritesArrowLeft: document.querySelector('.favorites__arrow-left'),
  favoritesList: document.querySelector('.favorites__list'),
  searchFavorites: document.querySelector('.search__favorites'),
  currentWeather: document.querySelector('.js-current-weather'),
  forecastToday: document.querySelector('.js-forecast__today-info-position'),
  sunriseToday: document.querySelector('.today__dawn'),
  sunsetToday: document.querySelector('.today__sunset'),
  body: document.querySelector('body'),
  geoModal: document.querySelector('.geolocation'),
  /* Одинаковые переменные. Надо разобраться */
  forecastToday: document.querySelector('.forecast__today'),
  forecastFiveDays: document.querySelector('.forecast__five-days'),
  forecastFiveDaysCity: document.querySelector('.five-days__city-name'),
  forecastFiveDaysList: document.querySelector('.five-days__list'),
  forecastMoreInfo: document.querySelector('.more-information__list'),
  switchDaysBtn: document.querySelector('.switch-days-btn'),
  currentWeather: document.querySelector('.current-weather'),
  citation: document.querySelector('.citation'),
  chartShow: document.querySelector('.chart__show'),
  chart: document.querySelector('#schedule'),
};
